version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: ChYo10!?!
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: addressbook_db
    ports:
      - "3306:3306"
    volumes:
      - test-mysql-data:/var/lib/mysql

  addressbook:
    container_name: addressbook-api
    build:
      context: .
    environment:
      MYSQL_HOST: db
      MYSQL_DB: addressbook_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ChYo10!?!
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  test-mysql-data:



