version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD_F: /run/secrets/mysql_root_password
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: addressbook_db
    ports:
      - "3306:3306"
    volumes:
      - test-mysql-data:/var/lib/mysql
    secrets:
      - mysql_root_password

  addressbook:
    container_name: addressbook-api
    image: joembiye/my-node-api:latest
    environment:
      MYSQL_HOST: db
      MYSQL_DB: addressbook_db
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_root_password
    depends_on:
      - db
    ports:
      - '3000:3000'
    secrets:
      - mysql_root_password

volumes:
  test-mysql-data:

secrets:
  mysql_root_password:
    file: my_pass.txt



